<br/>
<br/>
<p>Edit Subject</p>
<form method="POST">
    <label for="eid">Code</label>
    <input id="eid" name="eid" type="text"><br />

    <label for="ename">Name</label>
    <input id="ename" name="ename" type="text"><br />


    <label for="eteacher">Teacher</label>
    <input id="eteacher" name="eteacher" type="text"><br />

    <label for="enumber">Number</label>
    <input id="enumber" name="enumber" type="text"><br />


    <button type="submit">edit</button>

</form>