<br/>
<br/>
<p>Add subject</p>
<form method="POST">
    <label for="id">Code</label>
    <input id="id" name="id" type="text"><br />

    <label for="name">Name</label>
    <input id="name" name="name" type="text"><br />

    <label for="teacher">Teacher</label>
    <input id="teacher" name="teacher" type="text"><br />

    <label for="number">Number</label>
    <input id="number" name="number" type="text"><br />



    <button type="submit">Add</button>

</form>