<br/>
<br/>
<p>Edit Factory</p>
<form method="POST">
    <label for="ecode">Code</label>
    <input id="ecode" name="ecode" type="text"><br />

    <label for="ename">Name</label>
    <input id="ename" name="ename" type="text"><br />

    <label for="enumber">Number</label>
    <input id="enumber" name="enumber" type="text"><br />

    <label for="ebranch">Branch</label>
    <input id="ebranch" name="ebranch" type="text"><br />

    <label for="eaddress">Address</label>
    <input id="eaddress" name="eaddress" type="text"><br />

    <button type="submit">edit</button>

</form>