<br/>
<br/>
<p>Add factory</p>
<form method="POST">
    <label for="code">Code</label>
    <input id="code" name="code" type="text"><br />

    <label for="name">Name</label>
    <input id="name" name="name" type="text"><br />

    <label for="number">Number</label>
    <input id="number" name="number" type="text"><br />

    <label for="branch">Branch</label>
    <input id="branch" name="branch" type="text"><br />

    <label for="address">Address</label>
    <input id="address" name="address" type="text"><br />

    <button type="submit">Add</button>

</form>